# Generated by Django 3.2.5 on 2021-07-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='progress',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
