# Generated by Django 3.2.5 on 2021-07-21 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_tasks_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
