# Generated by Django 3.2.5 on 2021-08-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_tasks_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='submit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
