# Generated by Django 3.2.5 on 2021-09-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='progress',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
